# Preface {.unnumbered}

Science has always been a social and collective endeavor[@merton1996social]. Furthermore, from the Manhattan Project to the modern AI race, many of the most consequential advances in human knowledge have come not from lone investigators – but from big teams of scientists[@Coles2022]. In Fall of 2026, faculty, postdocs, and postdocs across multiple departments at the University of Florida leveraged these principles in a Fall 2026 seminar, titled Collective \[Artificial\] Intelligence in Science. Our goal? Leverage our own collective intelligence to rapidly make sense of one of the most pressing issues in contemporary research:

> **How is AI changing the nature of science, for better and for worse?**

![Structure of the University of Florida Fall 2026 seminar, titled Collective \[Artificial\] Intelligence in Science.](ClassStructure.png){#fig-seminar-structure fig-align="left"}

The seminar began with an introduction to big-team science – its evolution, competitive advantages, and relevance to the current moment[@Wuchty2007; @Coles2026]. From there, the course became a collective investigation, wherein we worked together to understand the newly disrupted nature of each stage of our research pipelines. This includes project management, literature review, idea development, data collection, analysis, writing, and dissemination[@Baumgartner2023]. To maintain balanced perspective, we alternated between deploying receptive vs. critical lens – identifying key resources, consensus statements, and areas of disagreement along the way. Throughout the semester, we organized our key insights into the resource you are viewing now: the 2027 Edition of the AI-in-Science Repository.

To develop this repository, each week followed a consistent structure (@fig-seminar-structure). First, we would select a component of the research pipeline to examine (e.g., data analysis). Next, we would spend one week compiling resources for understanding the emerging role of AI in that part of the research pipeline. In class, we engaged in peer-to-peer teaching – all with the goal of identifying the top 3 resources to include in the repository. Last, we used a live onlined voting platform to solicit, debate, and vote upon key takeaways for the week ([https://pol.is/](https://pol.is/signin)). The result is the 2027 Edition of the AI-in-Science Repository: a summary of our top resources, takeaways, and disagreements.